# Trivy plugin manifest <https://aquasecurity.github.io/trivy/v0.56/docs/plugin/developer-guide/>
name: "vens"
version: "0.1.0"
repository: github.com/venslabs/vens
maintainer: fahedouch
summary: Evaluate and prioritize vulnerabilities based on context
description: |-
  A Trivy plugin that evaluates and prioritizes vulnerabilities based on context using LLM.
  Supports VEX generation and report enrichment.
platforms:
  - selector:
      os: darwin
      arch: amd64
    uri: ./vens
    bin: ./vens
  - selector:
      os: darwin
      arch: arm64
    uri: ./vens
    bin: ./vens
  - selector:
      os: linux
      arch: amd64
    uri: ./vens
    bin: ./vens
  - selector:
      os: linux
      arch: arm64
    uri: ./vens
    bin: ./vens
